sudo: required
services:
  - docker

before_install:
  - docker build -t zavzam/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run zavzam/react-test npm test -- --coverage

after_success:
  - docker build -t zavzam/multi-client ./client
  - docker build -t zavzam/multi-nginx ./nginx
  - docker build -t zavzam/multi-server ./server
  - docker build -t zavzam/multi-worker ./worker
  # Log into the Docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push zavzam/multi-client
  - docker push zavzam/multi-nginx
  - docker push zavzam/multi-server
  - docker push zavzam/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-760354744479
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
